language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements/requirements.txt
addons:
  firefox: "41.0"
# command to run tests
script: xvfb-run -a nosetests