language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements/requirements.txt
  - export JASMINE_BROWSER=phantomjs
  - jasmine-ci
# command to run tests
script: nosetests